### ISSUE TITLE
Implement Vertex

### ISSUE THREAD

**Issue by TheVicBro** [laxitshahi/llm-proxy#30]
- Implement the API for Vertex
- Develop error handling

- Source: https://blog.canopas.com/how-to-create-your-own-chatbot-using-palm-2-model-chat-bison-001-fe99a2448f28

**Comment by laxitshahi** [comment]
School account blocks the use of google cloud and I have run out of credits in my main account.


![Image](https://github.com/laxitshahi/llm-proxy/assets/46412618/a952b8a1-003c-4ec7-9529-f9f443c37fd2)

- [ ] Email prof about permissions
- [ ] Create central account?
